apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo1
  labels:
    app: flaskdemo1
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: flaskdemo1
  template:
    metadata:
      labels:
        app: flaskdemo1
    spec:
      # ถ้าเป็น private image ให้ปลดคอมเมนต์บรรทัดล่างและตั้งค่า imagePullSecrets ให้ตรง
      # imagePullSecrets:
      # - name: dockerhub-cred
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
      containers:
      - name: flaskdemo1
        image: chanut8433/test:16
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 10001
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo1
  labels:
    app: flaskdemo1
spec:
  type: ClusterIP
  selector:
    app: flaskdemo1
  ports:
  - name: http
    port: 80
    targetPort: http
---
# (ตัวเลือก) ถ้ามี Ingress Controller แล้วค่อยใช้ส่วนนี่
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: flaskdemo1
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: flaskdemo1.local   # ← เปลี่ยนเป็นโดเมนจริง
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: flaskdemo1
#             port:
#               number: 80
