apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo1
  template:
    metadata:
      labels:
        app: flaskdemo1
    spec:
      containers:
      - name: flaskdemo1
        image: chanut8433/test-2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
